version: '2'

services:
  app:
    build: ./docker
    expose:
      - "9000"
    depends_on:
      - db
    volumes:
      - ./:/var/www/laravel-employees:cached

  nginx:
    build: ./docker/nginx
    ports:
      - "8000:80"
      - "443:443"
    depends_on:
      - app
    volumes_from:
      - app
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/sites-available/default.conf

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel_employees
    volumes:
      - db:/var/lib/mysql:cached

volumes:
  db:
